code --install-extension codezombiech.gitignore
code --install-extension donjayamanne.git-extension-pack
code --install-extension golang.go
code --install-extension jebbs.plantuml
code --install-extension mechatroner.rainbow-csv
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-ceintl.vscode-language-pack-ja
code --install-extension ms-mssql.mssql
code --install-extension tht13.python
code --install-extension waderyan.gitblame